### ISSUE TITLE
No view template found for custom viewtype in latest ez platform version

### ISSUE THREAD

**Issue by TFohrer** [netgen/ezplatform-site#81]
Hi Guys,

When using the site api (version  2.5.2 ) and the latest ez platform version (2.2.1) now I'm getting this error:

`An exception has been thrown during the rendering of a template ("No view template was set to render the view with the 'module' view type. Check your view configuration.").`

Although i have this config:

```
ezpublish:
    system:
        site_group:
            ngcontent_view:
                full:
                    scaya_default_pages:
                        template: :full:default_page.html.twig
                        match:
                            Identifier\ContentType: [scaya_pages_home, scaya_pages_detail]
                module:
                    youtube_video:
                        template: :modules:youtube-video.html.twig
                        match:
                            Identifier\ContentType: scaya_modules_youtube_video
                    detail_image_text:
                        template: :modules:detail-image-text.html.twig
                        match:
                            Identifier\ContentType: scaya_modules_detail_image_text 
```

That's the template part: 

```
...
{{ render_esi(controller('ng_content:viewAction', {
            'contentId': module,
            'viewType': 'module',
            'params':{
                'blockPosition': loop.index,
                'isRoot': false,
                'parentContentType': content.contentInfo.contentTypeIdentifier
            }})) }}
...
```

The automatic rendering of the viewtype `full` works, only the rendering via controller inside a template is not working somehow.
Using the default content rendering via `ez_content:viewAction` and using `content_view` in the config works fine, but then i don't get the site api functions. Even tried to replace the `ngcontent_view` with `content_view` 

Thanks in advance for your help
